# Generated by Django 5.0.6 on 2024-05-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='client',
            field=models.ManyToManyField(to='mailing_service.client', verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mailing_service.message', verbose_name='сообщение'),
        ),
    ]
