# Generated by Django 5.0.6 on 2024-05-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0003_alter_newsletter_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время окончания рассылки'),
        ),
    ]
