# Generated by Django 4.2.2 on 2024-06-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0004_alter_newsletter_end_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newslettertry",
            name="client",
        ),
        migrations.AddField(
            model_name="newslettertry",
            name="client",
            field=models.ManyToManyField(
                to="mailing_service.client", verbose_name="клиенты"
            ),
        ),
    ]
