# Generated by Django 4.2.2 on 2024-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_remove_newslettertry_client_newslettertry_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newslettertry",
            name="client",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="mailing_service.client",
                verbose_name="клиенты",
            ),
        ),
    ]
