# Generated by Django 4.2.2 on 2024-06-25 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0007_alter_newslettertry_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="message",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="mailing_service.message",
                verbose_name="сообщение",
            ),
        ),
    ]
