# Generated by Django 4.2.2 on 2024-06-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Добавьте содержимое", verbose_name="Содержимое"
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите изображение",
                        null=True,
                        upload_to="blog/images",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "views_count",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="Добавьте количество просмотров",
                        null=True,
                        verbose_name="Количество просмотров",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True,
                        help_text="Добавьте дату создания",
                        verbose_name="Дата создания",
                    ),
                ),
            ],
        ),
    ]
